### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by seokg** [seoungwugoh/opn-demo#6]
Hi, great work on video Inpainting!
I have two questions regarding the training of the network.

1. When training the network for video inpainting, how many reference images are needed, and how did you sample the frames?
2. Do you optimize the network for every peel or sum up all the losses and optimize after the hole region is completed?

Thank you.

**Comment by seoungwugoh** [comment]
Hi @seokg,
1. During training, we sample 5-frame clip and use one as the target and the others as the reference. 
2. We set the number of peeling-off operation (or recursion)  as a hyper-parameter (we used 5). After 5 iteration, the losses are sum up and back-proped. It is required for batch-training where each sample has different hole size.
